# Auto Merge Firefox Update
pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "author=mlyxshi"
      - files=darwin-version
    actions:
      merge:
        method: merge