keys:
  - &mac age14x4z8hzureysfnh3j2mtcjztvfy3klxh3md9pqfr3q7844vkq3gqrrczqd
  - &jp2 age102mj03x7e2pxxpspcc7ymha3z0upsnf0cwcgwk4jmft2qr4ddvustaye0r


creation_rules:
  - path_regex: key.yaml$
    key_groups:
    - age:
      - *mac
      - *jp2
