keys:
  - &m1 age1ww2sg52ryw2pjf5zs0jp4kqaw46nck5ykqj45zk5feverh6q036svg6qv8
  - &us1 age1m3r0y9czaf685jv434mkcv7krtzhlmkwx9snjlkg78kgjurzagjsm09aja
  - &jp2 age102mj03x7e2pxxpspcc7ymha3z0upsnf0cwcgwk4jmft2qr4ddvustaye0r
  - &jp4 age144jltkk3sp6nnd0gr8vgspte87uwvevs6q7ky6wvxdgppm6rlaks270nts
  - &kr  age1rftgm2trwzv53vyd7ld667efctqwzvcedw0uunshw3n4ard0ufcsrwunyq
  - &sw  age1ka4e8ku0dy7wdsdkm5xtex7d4sef3dzcm0kufst0sxmvxf4zk9usj2zaem
  - &tw  age1hju8jxy6edamuvgf2tl6ne2278s6kyvtt9egj9r89rs8f0yywgxqkw2k9p

creation_rules:
  - path_regex: key.yaml$
    key_groups:
    - age:
      - *m1
      - *us1
      - *jp2
      - *jp4
      - *kr
      - *sw
      - *tw