require("basic")
require("colorscheme")
require("keybindings")
require("autocmds")

require("lsp")
require("lsp/ui")
require("lsp/cmp")

require("plugin-config/bufferline")
require("plugin-config/nvim-tree")
require("plugin-config/lualine")
require("plugin-config/fidget")
require("plugin-config/dashboard")
require("plugin-config/project")
require("plugin-config/nvim-treesitter")
require("plugin-config/indent-blankline")
require("plugin-config/autopair")
require("plugin-config/modes")
require("plugin-config/comment")
require("plugin-config/gitsigns")
require("plugin-config/toggleterm")
require("plugin-config/whichkey")