name: "darwin build"
on:
  pull_request:
  push:
jobs:
  CI:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mlyxshi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    
    - name: Build and switch to nix-darwin env
      run: |
        nix build .#darwinConfigurations.M1-Non-Homebrew.system
        ./result/sw/bin/darwin-rebuild build --flake .#M1-Non-Homebrew