name: "deploy us1"
on:
  workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux
          trusted-public-keys = mlyxshi.cachix.org-1:yc7GPiryyBn0HfiCXdmO1ECWKBhfwrjdIFnRSA4ct7s=
          substituters = https://mlyxshi.cachix.org
    - uses: shimataro/ssh-key-action@v2
      with:
        key: '${{ secrets.SSH_PRIVATE_KEY }}'
        known_hosts: unnecessary
    - run: nix run github:serokell/deploy-rs -- -s .#us1
