name: "[Auto] deploy-rs build"
on:
  push:
  schedule:
    - cron: '00 00 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux
          trusted-public-keys = mlyxshi.cachix.org-1:yc7GPiryyBn0HfiCXdmO1ECWKBhfwrjdIFnRSA4ct7s= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://mlyxshi.cachix.org https://cache.nixos.org/
    - uses: cachix/cachix-action@v10
      with:
        name: mlyxshi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build github:serokell/deploy-rs