name: "deploy jp4"
on:
  workflow_dispatch

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v1
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          extra-platforms = aarch64-linux
          trusted-public-keys = mlyxshi.cachix.org-1:yc7GPiryyBn0HfiCXdmO1ECWKBhfwrjdIFnRSA4ct7s= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://mlyxshi.cachix.org https://cache.nixos.org/
    - uses: shimataro/ssh-key-action@v2
      with:
        key: '${{ secrets.SSH_PRIVATE_KEY }}'
        known_hosts: unnecessary
    - run: nix run github:serokell/deploy-rs -- -s .#jp4
