name: "[Auto] firefox darwin update"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: sudo apt install -y pcregrep jq
    - name: Shell Script
      run: |
        baseUrl="https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US"
        currentVersion=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/darwin-version.json"| jq ".version"|tr -d '"')

        latestUrl=$(curl --silent --output /dev/null  -w "%{redirect_url}" ${baseUrl})
        latestVersion=$(echo ${latestUrl}|pcregrep -o1 "releases\/(.*)\/mac")
        latestHash=$(nix-prefetch-url --name 'firefox-app-latest.dmg' ${baseUrl})

        jq --null-input --arg latestUrl $latestUrl  --arg latestVersion $latestVersion --arg latestHash $latestHash '{"url":${latestUrl},"version":${latestVersion},"sha256":$latestHash}'

        TG_TOKEN=${{ secrets.TG_TOKEN }}
        TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}
        TGUrl="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"

        if [ ${currentVersion} == ${latestVersion}  ]; then
          echo "current firefox version is latest"     
        else
          MESSAGE="current firefox version is outdated"        
          curl --silent --output /dev/null --request POST ${TGUrl} -d chat_id=${TG_CHAT_ID} -d text="${MESSAGE}"
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: update-patches
        delete-branch: true
        title: '[Auto] Update Firefox'
        body: |
          Update report
          - Updated with Firefox Version
          - Auto-generated by [create-pull-request][1]

        labels: |
          report
          automated pr
        assignees: mlyxshi
        reviewers: mlyxshi
