name: "[Auto] firefox darwin update"
on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  AutoUpdateFirefox:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.shell.outputs.latestVersion }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: sudo apt install -y pcregrep jq
    - name: Shell Script
      id: shell
      run: |
        baseUrl="https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US"
        currentVersion=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/darwin-version.json"| jq ".version"|tr -d '"')

        latestUrl=$(curl --silent --output /dev/null  -w "%{redirect_url}" ${baseUrl})
        latestVersion=$(echo ${latestUrl}|pcregrep -o1 "releases\/(.*)\/mac")
        latestHash=$(nix-prefetch-url --name 'firefox-app-latest.dmg' ${baseUrl})

        metaData=$(jq --null-input --arg latestUrl $latestUrl  --arg latestVersion $latestVersion --arg latestHash $latestHash '{"url":$latestUrl,"version":$latestVersion,"sha256":$latestHash}')

        echo "::set-output name=latestVersion::${latestVersion}"

        if [ ${currentVersion} == ${latestVersion}  ]; then
          echo "current firefox version is latest"     
        else
          echo ${metaData} >  ${GITHUB_WORKSPACE}/config/firefox/darwin-version.json
          echo "::set-output name=latestVersion::${latestVersion}"
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        branch: update-firefox
        delete-branch: true
        title: '[Auto] Update Firefox'
        body: |
          Update report
          - Updated with Firefox Version
          - Auto-generated by [create-pull-request][1]
        assignees: mlyxshi
        reviewers: mlyxshi




  SendTG:
    runs-on: ubuntu-latest
    needs: AutoUpdateFirefox
    steps:
    - name: send location message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_CHAT_ID }}
        token: ${{ secrets.TG_TOKEN }}
        message: |
          https://www.mozilla.org/en-US/firefox/${{needs.AutoUpdateFirefox.outputs.output1}}/releasenotes/
