name: "[Auto] firefox darwin"
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: |
        which pcregrep 
        which jq
    - run: sudo apt install -y pcregrep jq
    - run: |
        baseUrl="https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US"
        latestUrl=$(curl --silent --output /dev/null  -w "%{redirect_url}" ${baseUrl})
        latestVersion=$(echo ${latestUrl}|pcregrep -o1 "releases\/(.*)\/mac")
        latestHash=$(nix-prefetch-url --name 'firefox-app-latest.dmg' ${baseUrl})
    - run: |
        echo ${latestUrl}
        echo ${latestVersion}
        echo ${latestHash}


      