name: "[Auto] firefox darwin update"
on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  AutoUpdateFirefox:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.shell.outputs.latestVersion }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - run: sudo apt install -y pcregrep jq
    - name: Shell Script
      id: shell
      run: |
        baseUrl="https://download.mozilla.org/?product=firefox-latest&os=osx&lang=en-US"
        currentVersion=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/darwin-version.json"| jq ".version"|tr -d '"')

        latestUrl=$(curl --silent --output /dev/null  -w "%{redirect_url}" ${baseUrl})
        latestVersion=$(echo ${latestUrl}|pcregrep -o1 "releases\/(.*)\/mac")
        latestHash=$(nix-prefetch-url --name 'firefox-app-latest.dmg' ${baseUrl})

        metaData=$(jq --null-input --arg latestUrl $latestUrl  --arg latestVersion $latestVersion --arg latestHash $latestHash '{"url":$latestUrl,"version":$latestVersion,"sha256":$latestHash}')

        TG_TOKEN=${{ secrets.TG_TOKEN }}
        TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}
        TG_Url="https://api.telegram.org/bot${TG_TOKEN}/sendMessage"

        echo "::set-output name=latestVersion::${latestVersion}"

        if [ ${currentVersion} == ${latestVersion}  ]; then
          echo "current firefox version is latest"     
        else
          MESSAGE="current firefox version is outdated"        
          curl --silent --output /dev/null --request POST ${TG_Url} -d chat_id=${TG_CHAT_ID} -d text="${MESSAGE}"
          echo ${metaData} >  ${GITHUB_WORKSPACE}/config/firefox/darwin-version.json
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        branch: update-firefox
        delete-branch: true
        title: '[Auto] Update Firefox'
        body: |
          Update report
          - Updated with Firefox Version
          - Auto-generated by [create-pull-request][1]
        assignees: mlyxshi
        reviewers: mlyxshi
  
  SendTG:
    runs-on: ubuntu-latest
    needs: AutoUpdateFirefox
    steps:
    # - name: send location message
    #   uses: appleboy/telegram-action@master
    #   with:
    #     to: ${{ secrets.TG_CHAT_ID }}
    #     token: ${{ secrets.TG_TOKEN }}
    #     location: '24.9163213 121.1424972'
    #     venue: '35.661777 139.704051 竹北體育館 新竹縣竹北市'
    #     message: ${{needs.AutoUpdateFirefox.outputs.output1}}
    - run: ${{needs.AutoUpdateFirefox.outputs.output1}}