
name: "hx90 build"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17

    - uses: cachix/cachix-action@v10
      with:
        name: mlyxshi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.hx90.config.system.build.toplevel