name: "install-us0"
on:
  push:
    branches:
    - main
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - run: |
        SYSTEM_CLOSURE=$(nix eval --raw .#nixosConfigurations.us0.config.system.build.toplevel)
        sed "s/YOUR_SYSTEM_CLOSURE/$SYSTEM_CLOSURE/g" install-template.sh > install-us0.sh
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          install-us0.sh
