name: build kexec
on:
  workflow_dispatch
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v18
    - run: |
        nix build .#nixosConfigurations.kexec.config.system.build.kexecTree
    - uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        files: |
          result/kexec-boot
          result/initrd.gz
          result/bzImage