name: "oracle 4C24G build"
on:
  pull_request:
  push:
jobs:
  CI:
    runs-on: Linux-ARM64
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    - uses: cachix/cachix-action@v10
      with:
        name: mlyxshi
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - run: nix build .#nixosConfigurations.oracle.config.system.build.toplevel