name: "test darwin"
on:
  push:
    branches:
    - main

jobs:
  CI:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
      with:
        extra_nix_config: |
          allowBroken = true;
    - run: |
        nix build  .#darwinConfigurations."CI-TEST".system