name: "[Auto] update firefox version"
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  AutoUpdateFirefox:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.shell.outputs.latestVersion }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    # - run: sudo apt install -y pcregrep jq
    - name: Shell Script
      id: shell
      run: |

        latestVersion=$(curl --silent https://product-details.mozilla.org/1.0/firefox_versions.json | jq '.LATEST_FIREFOX_VERSION' | tr -d '"')
        currentVersion=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/version.json"| jq ".version" | tr -d '"')       
        
        currentDarwinHash=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/version.json"| jq ".darwin.sha256" | tr -d '"') 
        latestDarwinUrl="https://download-installer.cdn.mozilla.net/pub/firefox/releases/${latestVersion}/mac/en-US/Firefox%20${latestVersion}.dmg"
        latestDarwinHash=$(nix-prefetch-url  --name "firefox-${latestVersion}.dmg" "${latestDarwinUrl}")

        if [ $currentVersion == $latestVersion && $currentDarwinHash == $latestDarwinHash && $currentLinuxHash == $latestLinuxHash ]; then

          echo "current firefox version is latest"
          echo "::set-output name=latestVersion::0"     

        else

          jq --null-input --arg latestDarwinUrl $latestDarwinUrl  \
            --arg latestVersion $latestVersion  \
            --arg latestDarwinHash $latestDarwinHash \
            '{ "version": $latestVersion, "darwin": { "url": $latestDarwinUrl,"sha256": $latestDarwinHash}, "description": "[Auto-Generated] Firefox Stable Version" }' \
            >  ${GITHUB_WORKSPACE}/config/firefox/version.json
          echo "::set-output name=latestVersion::${latestVersion}"
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        branch: update-firefox
        title: '[Auto] Update Firefox'
        body: |
          Update report
          - Updated with Firefox Version
          - Auto-generated
        assignees: mlyxshi
        reviewers: mlyxshi




  SendTG:
    runs-on: ubuntu-latest
    needs: AutoUpdateFirefox
    if: needs.AutoUpdateFirefox.outputs.output1 !=0
    steps:
    - name: send firefox info
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_CHAT_ID }}
        token: ${{ secrets.TG_TOKEN }}
        message: |
          Firefox Update: ${{needs.AutoUpdateFirefox.outputs.output1}}

          https://www.mozilla.org/en-US/firefox/${{needs.AutoUpdateFirefox.outputs.output1}}/releasenotes/
