name: "[Auto] update firefox version"
on:
  workflow_dispatch:
  schedule:
    - cron: '00 00 * * *'

jobs:
  AutoUpdateFirefox:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.shell.outputs.latestVersion }}
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v17
    # - run: sudo apt install -y pcregrep jq
    - name: Shell Script
      id: shell
      run: |

        lastestVersion=$(curl --silent https://product-details.mozilla.org/1.0/firefox_versions.json | jq '.FIREFOX_NIGHTLY' | tr -d '"')
        currentVersion=$(curl --silent "https://raw.githubusercontent.com/mlyxshi/flake/main/config/firefox/version.json"| jq ".version" | tr -d '"')       

        if [ ${currentVersion} == ${latestVersion}  ]; then

          echo "current firefox version is latest"
          echo "::set-output name=latestVersion::0"     

        else

          latest-Darwin-Url='https://download.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-${lastestVersion}.en-US.mac.dmg'
          latest-Linux-Url='https://download.cdn.mozilla.net/pub/firefox/nightly/latest-mozilla-central/firefox-${lastestVersion}.en-US.linux-x86_64.tar.bz2'
          latest-Darwin-Hash=$(nix-prefetch-url latest-Darwin-Url)
          latest-Linux-Hash=$(nix-prefetch-url latest-Linux-Url)

          jq --null-input --arg latest-Darwin-Url $latest-Darwin-Url  \
          --arg latest-Linux-Url $latest-Linux-Url \
          --arg latestVersion $latestVersion \
          --arg latest-Darwin-Hash $latest-Darwin-Hash \
          --arg latest-Linux-Hash $latest-Linux-Hash \
          '{"version":$latestVersion, "darwin-url":$latest-Darwin-Url, "darwin-sha256":$latest-Darwin-Hash, "linux-url":$latest-Linux-Url, "linux-sha256":$latest-Linux-Hash}' \
          >  ${GITHUB_WORKSPACE}/config/firefox/darwin-version.json
          echo "::set-output name=latestVersion::${latestVersion}"
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.GIT_TOKEN }}
        branch: update-firefox
        delete-branch: true
        title: '[Auto] Update Firefox'
        body: |
          Update report
          - Updated with Firefox Version
          - Auto-generated
        assignees: mlyxshi
        reviewers: mlyxshi




  SendTG:
    runs-on: ubuntu-latest
    needs: AutoUpdateFirefox
    if: needs.AutoUpdateFirefox.outputs.output1 !=0
    steps:
    - name: send firefox info
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TG_CHAT_ID }}
        token: ${{ secrets.TG_TOKEN }}
        message: |
          Firefox Update: ${{needs.AutoUpdateFirefox.outputs.output1}}

          https://www.mozilla.org/en-US/firefox/${{needs.AutoUpdateFirefox.outputs.output1}}/releasenotes/
