keys:
  - &m1 age1ww2sg52ryw2pjf5zs0jp4kqaw46nck5ykqj45zk5feverh6q036svg6qv8
  - &hx90 age1p0f5vtkxqw30r6t752rhh27ye74rxe5cdcslyexhdsn63sx2d9yqw0kvnt
  - &us1 age1yvq398q22lwwsq3v4js3kftm4j25qfwjvy9uakw6r23r90vd7vzs3ekhuj
  - &jp2 age102mj03x7e2pxxpspcc7ymha3z0upsnf0cwcgwk4jmft2qr4ddvustaye0r
  - &jp4 age144jltkk3sp6nnd0gr8vgspte87uwvevs6q7ky6wvxdgppm6rlaks270nts
  - &kr  age1rftgm2trwzv53vyd7ld667efctqwzvcedw0uunshw3n4ard0ufcsrwunyq
  - &sw  age1ka4e8ku0dy7wdsdkm5xtex7d4sef3dzcm0kufst0sxmvxf4zk9usj2zaem
  - &au  age1awfr49prteacfepzmqnna4knpka9xjxa2hv4j293avpd9ru4lfesamaqh4

  - &jp3 age1wxm5q3edkwnt7ntm9hespg7gslk882pws6ccywcrjt9e56smdvussuenrx

creation_rules:
  - path_regex: key.yaml$
    key_groups:
    - age:
      - *m1
      - *hx90
      - *us1
      - *jp2
      - *jp4
      - *kr
      - *sw
      - *au

      - *jp3